### ISSUE TITLE
Member data in an observable room with historical messages enabled

### ISSUE THREAD

**Issue by nicko** [ScaleDrone/Scaledrone-Swift#11]
I'm using Scaledrone for a chat app I'm building and I'm playing with the historical messages feature. I've noticed that when I connect a new client, the historical messages played back to `ScaledroneRoom.scaledroneRoomDidReceiveMessage(room, message, member)` do not contain any member data.

Hopefully I've just missed something and this is not an issue at all!

**Issue Description**
When loading historical messages, Scaledron initializes with an `observable_members` event which sends all the current members in my observable room. If a member has previously logged on and created a message and subsequently logged off again, they are not returned in this list.

The result is that when historical messages are returned in the subsequent `history_message` events from the server, there is no current member with a matching Client ID and the `member` argument is `nil`. 

**Possible Solutions**
I am happy to store the list of members in my own db and simply match them up with messages as they are received, but the `client_id` property available in the message in `handleHistoryMessage` -> `delegatePublishMessage` is not passed through the subsequent `scaledroneRoomDidReceiveMessage(room, message, member)`.

Or

Can we have an extra data store on Scaledrone's servers for historical member data and have that transmitted in a similar form to the `observable_members` event before the `history_message` events start being sent?

**Comment by herkyl** [comment]
Hey @nicko !

You're quite right, the `member` argument gets passed if the user is currently online and available in the observable rooms. In the longer term I think it would be a better solution for us to save the historic member data along with the historic messages. As for a quickfix it would make sense to pass along the `client_id` as an argument, so you could use that for a lookup.

**Comment by marinbenc** [comment]
Hi @nicko 

`scaledroneRoomDidReceiveMessage(room:message:member)` was renamed to `scaledroneRoomDidReceiveMessage(room:message:)` and message is now of type `ScaledroneMessage` which includes the member, the member and message IDs, the message's time as well as the data that was sent.

You can find the existing message data in `message.data`:

```
func scaledroneRoomDidReceiveMessage(room: ScaledroneRoom, message: ScaledroneMessage) {
    if message.member != nil {
        // This message was sent to an observable room
        // This message was sent through the socket API, not the REST API
        print("Received message from member:", message.memberID as Any)
    }
    
    let data = message.data
    
    if let messageData = data as? [String: Any] {
        print("Received a dictionary:", messageData)
    }
    if let messageData = data as? [Any] {
        print("Received an array:", messageData)
    }
    if let messageData = data as? String {
        print("Received a string:", messageData)
    }
}
```

I hope this helps you with your issue.
