### ISSUE TITLE
CocoaPods can't find version 0.5.2

### ISSUE THREAD

**Issue by CodingAleCR** [ScaleDrone/Scaledrone-Swift#13]
Hi, I'm trying to use the version 0.5.2 but it seems like Cocoapods only is able to identify versión 0.5.0. I've tried pod update and even hardcoding the version but it ends up with this:

```
None of your spec sources contain a spec satisfying the dependency: `Scaledrone (~> 0.5.2)`.
```

 Any thoughts?

**Comment by herkyl** [comment]
This should now be fixed! Closing it for now, feel free to reopen if still having trouble.
